### ISSUE TITLE
Telegram not working

### ISSUE THREAD

**Issue by pablogomez93** [dylanpdx/vxtiktok#1]
Hi! I tried this on telegram but it won't work.

**Comment by dylanpdx** [comment]
![image](https://user-images.githubusercontent.com/1337360/188944621-90a18aa6-59ab-4fbe-8b83-f1942528bd4e.png)
Just tested and it's working fine for me? It might be a specific video causing the issue

**Comment by dylanpdx** [comment]
Feel free to re-open the issue if it's still occurring. A video link that doesn't work would be nice to know also

**Comment by pablogomez93** [comment]
Hi! I have found a non working link.

When I take this link https://vm.tiktok.com/ZMFj9FYkY/

And change it into this:
https://vm.vxtiktok.com/ZMFj9FYkY/

It does not work.

![Screenshot_20221011-235802_Telegram](https://user-images.githubusercontent.com/7672584/195239521-10c70df6-1140-4500-b33c-9145f6f11f70.jpg)

It gets just an image like that

**Comment by dylanpdx** [comment]
This should be fixed now but old links might still fail to embed for a while as Telegram keeps them cached
