### ISSUE TITLE
vm.tiktok.com support

### ISSUE THREAD

**Issue by rafalohaki** [dylanpdx/vxtiktok#101]
www.tiktok.com redirect is working but vm.tiktok.com is not 
for example https://redirect.com/ZGJEytV2E is not working but
https://redirect.com/@daily.dose.of_cs/video/7296177730775731489 is working

https://vm.tiktok.com/ZGJEytV2E/ is mobile version of https://www.tiktok.com/@daily.dose.of_cs/video/7296177730775731489

vm.tiktok.com is a copied link using tiktok app

**Comment by dylanpdx** [comment]
The correct link to use is always by replacing 'tiktok' in the URL with 'vxtiktok'. If a link is `https://vm.tiktok.com/...`, the replacement would be `https://vm.vxtiktok.com/...`
![image](https://github.com/dylanpdx/vxtiktok/assets/1337360/ecbf29c6-f5e6-4db9-9302-49b07e753015)

**Comment by rafalohaki** [comment]
thanks, its working. needed to add second domain vm.redirect.com
