### ISSUE TITLE
Add localized URLs to the server

### ISSUE THREAD

**Issue by BloodDragooner2** [dylanpdx/vxtiktok#11]
Recently found out of a huge list of domains Tiktok uses for share links 
![here](https://user-images.githubusercontent.com/117775945/201454989-ecbf75cd-9af9-4899-9055-b649382ddadf.png)
[Found on this github gist](https://gist.github.com/adryd325/2d5d37ba2863cd6636e4a3f26a14b0d1)

**Comment by dylanpdx** [comment]
The service should still work with all subdomains TikTok has, except maybe tiktokv and link.e.tiktok

**Comment by BloodDragooner2** [comment]
Ah, I see, then maybe I was doing it wrong, 'cause it didn't work yesterday...
