### ISSUE TITLE
Repeatedly seeing "failed to get video data" errors on videos and slideshows 

### ISSUE THREAD

**Issue by GeorgeWL** [dylanpdx/vxtiktok#114]
https://vm.vxtiktok.com/ZGefAFtWw/ - example

![Screenshot_2024-03-12-18-40-36-93_572064f74bd5f9fa804b05334aa4f912.jpg](https://github.com/dylanpdx/vxtiktok/assets/5931248/dc4e41e4-e369-457c-acd7-6fe0768038c1)

**Comment by kpopdev** [comment]
vxtiktok is down

**Comment by walteryin0** [comment]
seems like its down on all `tiktok.com`, `vt.tiktok.com`, `vm.tiktok.com`

**Comment by dylanpdx** [comment]
Looking into this

**Comment by dylanpdx** [comment]
Should be fixed now.

**Comment by GeorgeWL** [comment]
> Should be fixed now. 

Yes, though a new issue has arisen lately, I'll make a ticket for it
