### ISSUE TITLE
Showing only text and no video

### ISSUE THREAD

**Issue by GeorgeWL** [dylanpdx/vxtiktok#115]
On some but not all videos, it's not embedding the video, only the description text

![Screenshot_2024-03-18-10-07-14-55_572064f74bd5f9fa804b05334aa4f912.jpg](https://github.com/dylanpdx/vxtiktok/assets/5931248/30f55b82-7a34-4975-b990-3806e723d3b8)

Example URL: https://vm.vxtiktok.com/ZGePDUdkv/

**Comment by dylanpdx** [comment]
Seems to be a Discord bug which I've just reported to them. Unfortunately can't be worked around until they fix things on video embeds, due to the way Tiktok links are formatted. Will keep you updated on Discord's response

**Comment by jlram** [comment]
Hi @dylanpdx I think it's happening in Telegram too

**Comment by 123jjck** [comment]
This is due to https://github.com/yt-dlp/yt-dlp/issues/9506
[There is a working workaround](https://github.com/yt-dlp/yt-dlp/issues/9506#issuecomment-2023661357)

**Comment by dylanpdx** [comment]
Until this is merged into main yt-dlp, I've included the fork with the workaround as a dependency.
Fix seems to be working with the original linked video:
![image](https://github.com/dylanpdx/vxtiktok/assets/1337360/8e861769-a369-4cfa-a434-b72423d59471)

**Comment by StevenKobza** [comment]
> there's a similar issue, the embeds are no longer working on slideshow type content, instead only showing the text from the caption I'll make anew issue for it later today

Hey just wanted to see if you had made a new issue cause this is still going on, so just wanted to double check before I created one.

**Comment by GeorgeWL** [comment]
Ah yeah, I thought it was unconnected, but I just noticed this issue has reintroduced itself

**Comment by StevenKobza** [comment]
Hello @123jjck have you heard anything new about this information with regards to YT-DLP?

**Comment by GeorgeWL** [comment]
maybe check with the devs of [fxTikTok.com](https://github.com/okdargy/fxTikTok) they seem to not be having this issue so might have some tips
