### ISSUE TITLE
Video not embeded in Discord anymore

### ISSUE THREAD

**Issue by Lexsah** [dylanpdx/vxtiktok#130]
Hello, I noticed that since a few days, the vxtiktok doesn't show as the embedded video in discord anymore, instead there are the thumbnail, title, #, and stats.

Tried : 
- https://vm.tiktok.com/ZGeuaBa6A/ -> https://vm.vxtiktok.com/ZGeuaBa6A/
- https://www.tiktok.com/@semi_pro_3d/video/7355957273778261290 -> https://vm.vxtiktok.com/@semi_pro_3d/video/7355957273778261290 (with this one, there is not even the thumbnail but the stats are here)
- https://www.tiktok.com/@semi_pro_3d/video/7355957273778261290?_r=1&_t=8lSnwhZnf97 -> https://www.vxtiktok.com/@semi_pro_3d/video/7355957273778261290?_r=1&_t=8lSnwhZnf97

**Comment by StevenKobza** [comment]
Replying to this to reference issue #115 as it was the same issue then.

**Comment by dylanpdx** [comment]
Looking into it
