### ISSUE TITLE
Embeds working but they are stretched 

### ISSUE THREAD

**Issue by kodurrrr** [dylanpdx/vxtiktok#6]
I tried the service , it works really good and embeds the links but shows the videos stretched , example : 
![Screenshot_20221019-211413](https://user-images.githubusercontent.com/96727508/196833645-c9580bd0-4009-41ae-8673-bb498761fb2b.jpg)

**Comment by dylanpdx** [comment]
Should be fixed now

**Comment by kodurrrr** [comment]
> Should be fixed now

yeah it works , thanks !
