### ISSUE TITLE
Video stats seem to be random

### ISSUE THREAD

**Issue by kokoropaint** [dylanpdx/vxtiktok#64]
Thank you for this service, it's been very helpful:)

For some reason, the video stats provided in the embed are almost always incorrect (for example [this video](https://www.tiktok.com/t/ZT8JAKVpX/) only has about 5,000 likes)
![Screenshot_20230620_185748_Discord](https://github.com/dylanpdx/vxtiktok/assets/37761120/16e7caa2-cdcb-4bc6-9a0d-03fe1ebbbe46)

This seems to happen with both short and long tiktok links (the ones which contain the poster's username.)

**Comment by dylanpdx** [comment]
Issue was on the back end and should be fixed soon as Discord takes a while to update their cache!
Please close this if it starts working as normal :)

**Comment by kokoropaint** [comment]
Working on Discord now :)
