### ISSUE TITLE
Show video description in embed

### ISSUE THREAD

**Issue by kokoropaint** [dylanpdx/vxtiktok#65]
Showing the video description (maybe other information like username and duet/stitch links displaying like in the app if it's possible to get?) in the text of the embed would be nice.

[Stitch example](https://www.tiktok.com/t/ZT8JA3XPj/)
![showing the tiktok description in app](https://files.catbox.moe/m3rd6r.jpg)

**Comment by dylanpdx** [comment]
This is an issue on Discord's end. The video's description is already sent as part of the data, but discord for some reason hides it on video embeds. I could work around it by sticking it somewhere else but space is limited on the other fields I can modify.

Telegram for example parses the description field correctly and displays it, but hides the other data
![image](https://github.com/dylanpdx/vxtiktok/assets/1337360/f65f20dc-2f4b-4a03-a523-bc308928760c)
