### ISSUE TITLE
Incorrect video url for some videos

### ISSUE THREAD

**Issue by 123jjck** [dylanpdx/vxtiktok#75]
When trying to download some videos (for example https://vt.viktok.com/ZSLmKFSQH/ , https://vt.tiktok.com/ZSLmnxU5B/ and https://vt.tiktok.com/ZSLueL36h/), the provided URL is incorrect:
![image](https://github.com/dylanpdx/vxtiktok/assets/48408304/7fe19078-a065-4d65-9615-910008be0f46)
![image](https://github.com/dylanpdx/vxtiktok/assets/48408304/bcc830ea-a57e-495a-b560-37c3d8fd019f)

But using yt-dlp with the --get-url option gives the correct direct link for the same videos:
![image](https://github.com/dylanpdx/vxtiktok/assets/48408304/1ed2573c-cb76-4987-898b-639575e2a601)
![image](https://github.com/dylanpdx/vxtiktok/assets/48408304/576caa61-e4d5-43c5-add0-afb6294e244e)

**Comment by dylanpdx** [comment]
URLs should be correct from now on! Re-open if there are any issues though

**Comment by 123jjck** [comment]
Now it gives correct URLs (i checked again with manual requests), but for the videos https://vt.tiktok.com/ZSLmnxU5B/ and https://vt.tiktok.com/ZSLmKFSQH/ Telegram only shows preview image for some reason (i updated Telegram link preview cache after fix)

https://github.com/dylanpdx/vxtiktok/assets/48408304/c283ad8b-cb83-4e7b-82b8-bb39a5f08f5a
