### ISSUE TITLE
If possible, retrieve TikTok video without the animated watermark

### ISSUE THREAD

**Issue by Tiagoquix** [dylanpdx/vxtiktok#96]

**Comment by Apocolypto** [comment]
tiktxk retrieves videos without the watermark, but lacks slideshow support compared to vxtiktok

https://github.com/Britmoji/tiktxk

**Comment by dylanpdx** [comment]
Other messaging services let you save the video, and there are modifications to Discord and browser extensions that let you do this as well.
![image](https://github.com/dylanpdx/vxtiktok/assets/1337360/4adf45d8-2bb0-431d-a85a-c1fe787e6be5)
